### ISSUE TITLE
March 2022 Project: Pydra

### ISSUE THREAD

**Issue by effigies** [brainhack-boston/projects#20]
Will update with additional participants and specific goals as they are established.

See https://github.com/nipype/pydra/issues?q=is%3Aissue+is%3Aopen+label%3Ahackathon / https://github.com/orgs/nipype/projects/1

Participants: @djarecka @effigies

**Comment by djarecka** [comment]
if you want to play with pydra, you can start here: https://github.com/nipype/pydra-tutorial

**Comment by effigies** [comment]
Result: https://github.com/nipype/pydra/pull/516
